CREATE PROCEDURE NOTLISTESI
AS
SELECT NOTID,AD + ' ' + SOYAD AS 'AD SOYAD', DERSAD AS 'DERS ADI', SINAV1,SINAV2,SINAV3,ORTALAMA,DURUM FROM dbo.M_NOTLAR
INNER JOIN dbo.M_OGRENCI ON M_OGRENCI.ID = M_NOTLAR.OGR
INNER JOIN dbo.M_DERSLER ON M_DERSLER.DERSID = M_NOTLAR.DERS


EXECUTE dbo.NOTLISTESI