USE [AdventureWorks]
GO

/****** Object:  Table [dbo].[M_KULUPLER]    Script Date: 10.06.2022 11:35:32 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[M_KULUPLER](
	[KULUPID] [SMALLINT] IDENTITY(1,1) NOT NULL,
	[KULUPAD] [VARCHAR](50) NULL,
 CONSTRAINT [PK_M_KULUPLER] PRIMARY KEY CLUSTERED 
(
	[KULUPID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO


