USE [AdventureWorks]
GO

/****** Object:  Table [dbo].[M_NOTLAR]    Script Date: 10.06.2022 11:35:40 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[M_NOTLAR](
	[NOTID] [INT] IDENTITY(1,1) NOT NULL,
	[OGR] [INT] NULL,
	[DERS] [INT] NULL,
	[SINAV1] [SMALLINT] NULL,
	[SINAV2] [SMALLINT] NULL,
	[SINAV3] [SMALLINT] NULL,
	[ORTALAMA] [DECIMAL](5, 2) NULL,
	[DURUM] [BIT] NULL,
 CONSTRAINT [PK_M_NOTLAR] PRIMARY KEY CLUSTERED 
(
	[NOTID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[M_NOTLAR]  WITH CHECK ADD  CONSTRAINT [FK_M_NOTLAR_M_DERSLER] FOREIGN KEY([DERS])
REFERENCES [dbo].[M_DERSLER] ([DERSID])
GO

ALTER TABLE [dbo].[M_NOTLAR] CHECK CONSTRAINT [FK_M_NOTLAR_M_DERSLER]
GO

ALTER TABLE [dbo].[M_NOTLAR]  WITH CHECK ADD  CONSTRAINT [FK_M_NOTLAR_M_OGRENCI] FOREIGN KEY([OGR])
REFERENCES [dbo].[M_OGRENCI] ([ID])
GO

ALTER TABLE [dbo].[M_NOTLAR] CHECK CONSTRAINT [FK_M_NOTLAR_M_OGRENCI]
GO


