USE [AdventureWorks]
GO

/****** Object:  Table [dbo].[M_OGRENCI]    Script Date: 10.06.2022 11:35:47 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[M_OGRENCI](
	[ID] [INT] IDENTITY(1,1) NOT NULL,
	[AD] [VARCHAR](20) NULL,
	[SOYAD] [VARCHAR](20) NULL,
	[FOTOGRAF] [VARCHAR](20) NULL,
	[OGRKULUP] [SMALLINT] NULL,
	[SEHIR] [VARCHAR](20) NULL,
 CONSTRAINT [PK_M_OGRENCI] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[M_OGRENCI]  WITH CHECK ADD  CONSTRAINT [FK_M_OGRENCI_M_KULUPLER] FOREIGN KEY([OGRKULUP])
REFERENCES [dbo].[M_KULUPLER] ([KULUPID])
GO

ALTER TABLE [dbo].[M_OGRENCI] CHECK CONSTRAINT [FK_M_OGRENCI_M_KULUPLER]
GO


